services:
  app:
    build:
      context: .
      target: dev
    ports:
      - "8080:80"
      - "8443:443"
    volumes:
      - ./:/app
      - caddy_data:/data
      - caddy_config:/config
    environment:
      APP_ENV: dev
      APP_DEBUG: 1
    tty: true

volumes:
  caddy_data:
  caddy_config:#
